title: Progressive Web Apps
description: >-
  Kursen fokuserar på grunderna i en PWA genom att göra “traditionella”
  webbappar installerbara (inklusive ikoner). De blir också snabbare med   
  service workers för cachning och offlinefunktionalitet.
template:
  repo: progressive-web-apps-template
  name: progressive-web-apps
steps:
  - title: 0. Hello World
    description: Välkommen till kursen
    video: 'https://player.vimeo.com/video/651177074?h=7026a5682f&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479'
    event: watch
  - title: 0.1 Https
    description: I detta steg så installerar vi https på vår localhost
    video: 'https://player.vimeo.com/video/651177074'
    event: watch
